### ISSUE TITLE
curly brackets

### ISSUE THREAD

**Issue by Mhall1337** [learn-co-curriculum/phase-1-object-ball#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.
https://learning.flatironschool.com/courses/4330/assignments/134989?module_item_id=280607

## Describe the bug
the function homeTeamName() does not have its beginning curly bracket and throws a syntax error 

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

## Screenshots
![image](https://user-images.githubusercontent.com/84192755/129629907-383fdb48-99dd-44c8-8bd1-cd9cefa63b95.png)

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [ ] Linux

**Comment by ihollander** [comment]
Good catch @Mhall1337 ! This has been fixed: https://github.com/learn-co-curriculum/phase-1-object-ball/commit/8436d9b991ebc43349acb3edb509c76a4f5a13d5
