### ISSUE TITLE
No ability to submit optional lab via codespace (button is not there at all)

### ISSUE THREAD

**Issue by Chris10Garcia** [learn-co-curriculum/phase-1-object-ball#1]
### Canvas Link

https://learning.flatironschool.com/courses/6190/assignments/225562

### Concern

I completed the bonus object ball lab but i don’t see the codespace link to submit on the bottom. I DO see the old “submit button” on the top right to submit the repo page link. I tried submitting it that way. my canvas shows it’s submitted but not completed / graded. I tried using my repo’s link from the browser and the repo’s .git link… and neither works for showing it completed.

The lab mentions to have it graded / count as complete, to submit via codespace. but the button does not appear at all. I attached screenshots.

![Screenshot 2023-01-19 at 11 35 21 AM](https://user-images.githubusercontent.com/10578405/213500025-85e34fd0-e15a-41e9-bd8f-60640a2d29d0.png)
![Screenshot 2023-01-19 at 11 35 39 AM](https://user-images.githubusercontent.com/10578405/213500037-21bcb068-b4e8-439c-b3b5-f8cd01a8f9c4.png)

**Comment by lizbur10** [comment]
Hi @Chris10Garcia - thanks for bringing this to our attention! The CodeGrade button should now be present on the lesson page. 💙
