### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ahmadalashtar** [learn-co-curriculum/phase-1-object-ball#4]
Continuous use of 'a object' instead of 'an object'

**Comment by lizbur10** [comment]
Hi @ahmadalashtar01 ! Thanks for bringing this to our attention - it has now been fixed. Note that you may not see the corrections in your Canvas course but they will be in place for future cohorts. You can see the updates in the README.md file in this repo.

Thanks for contributing to the Flatiron School curriculum 💙
