### ISSUE TITLE
Wrong Function Name

### ISSUE THREAD

**Issue by ajs-amandasmith** [learn-co-curriculum/phase-1-object-ball#9]
### Canvas Link

https://learning.flatironschool.com/courses/4978/assignments/167546?module_item_id=362176

### Concern

In the second paragraph of **Step 2: Building Functions**, this sentence is there:
We can call the gameHash function inside of our homeTeamName function and operate on the object:

I believe **gameHash** is supposed to be **gameObject**, as this is the first time gameHash has been mentioned and in the following code example, gameObject is shown but there is now gameHash.
![Screen Shot 2022-03-04 at 7 57 20 PM](https://user-images.githubusercontent.com/37988788/156863337-29e991cd-7aba-4b71-83a9-094e185edc29.png)

**Comment by lizbur10** [comment]
Hi there! Thanks for catching this - the error has now been fixed.

Thanks for contributing to the Flatiron School. curriculum 💙
